//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using CadastroDeClientes.Domain;
using LinqToDB;
using LinqToDB.Configuration;
using System.Linq;

namespace CadastroDeClientes.Infra.DataModel
{
    /// <summary>
    /// Database       : dbClientes
    /// Data Source    : INVENT044\SAP
    /// Server Version : 14.00.2037
    /// </summary>
    public partial class DbClientesDB : LinqToDB.Data.DataConnection
	{
		public ITable<Cliente> Clientes { get { return this.GetTable<Cliente>(); } }

		public DbClientesDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbClientesDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbClientesDB(LinqToDbConnectionOptions<DbClientesDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	public static partial class TableExtensions
	{
		public static Cliente Find(this ITable<Cliente> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
